service: quotes #name this whatever you want

provider:
 name: aws
 runtime: python3.10
 region: us-east-2
 memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'
package:
  exclude:
    - node_modules/**
    - env/**

